config/routes.rb
Rails.application.routes.draw do
  resources :tictactoes
  devise_for :users

   root 'welcome#index'
   
  post "welcome/create" => "welcome#create"
  get "game_change/:id" => "welcome#game_change", :as => :game_change

end

app/models/tictactoe.rb
class Tictactoe < ActiveRecord::Base
  belongs_to :user
  
  validates :user_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
       
  has_one :tictactoe
  
  
       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
  
#  def after_sign_in_path_for(resource)
#    
#    
#    redirect_to root_path
#  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :set_default_values, :only => [:index]
  before_filter :initialize_value, :only => [:create]

  GAME_SET = [9, 16, 25]
  
  def index
    Tictactoe.new(:total => 0, :pass => 0, :fail => 0, :user => current_user).save if current_user.tictactoe.nil?
  end
  
  def game_change
    if GAME_SET.include? (params[:id].to_i)
      session[:game_id] = params[:id].to_i
    end
    redirect_to root_path
  end
  
  def create
    add_user_picked_value(params[:id])
    @user_won = TicTacToeRule.is_user_won?(@user_picked_values, @possible_way_set)
    get_host_choose_number unless @user_won
    game_over if @user_won || @host_won
    
    respond_to do | format|
      msg = { :status => "ok", :message => "Success!", :host_choose_numbser => @choose_number, :user_won => @user_won, :host_won => @host_won || false }
      format.json {render :json => msg}
    end
  end
  
  def add_user_picked_value(id)
    @user_picked_values << id.to_i
    update_user_values
    @valid_numbers = (1..@game_id.to_i).to_a if @valid_numbers.nil?
    @valid_numbers.to_a.delete(id.to_i)
    update_valid_numbers
  end

  def get_host_choose_number
    @choose_number = possible_number_to_win
    unless @choose_number.nil?
      @valid_numbers.delete(@choose_number.to_i)
      update_valid_numbers
      @host_picked_values << @choose_number
      update_host_values
    end
    @host_won = TicTacToeRule.find_possiblity?(@host_picked_values, @choose_number, @possible_way_set)
  end
  
  def possible_number_to_win
    @valid_numbers.each do |number|
      return number if TicTacToeRule.find_possiblity?(@host_picked_values, number, @possible_way_set)
    end
    possible_number_to_lose
  end

  def possible_number_to_lose
    @valid_numbers.each do |number|
      return number if TicTacToeRule.find_possiblity?(@user_picked_values, number, @possible_way_set)
    end
    get_a_number_to_block
  end

  def get_a_number_to_block
    @valid_numbers.each do |number|  
      record = TicTacToeRule.get_block_number(@user_picked_values, @host_picked_values, @possible_way_set, number) 
      return number if record >= (@game_value.to_i - 1)
    end
    get_possible_way_to_win
  end

  def get_possible_way_to_win
    possible_list = {}
    @valid_numbers.each do |number|
      result = TicTacToeRule.get_win_possiblity_number(@valid_numbers, @host_picked_values, @possible_way_set, number)
      possible_list[number] = result
    end 
    TicTacToeRule.get_win_number(possible_list)
  end
  
  def game_over
    tictactoe = current_user.tictactoe
    tictactoe.pass = tictactoe.pass.to_i + 1 if @user_won
    tictactoe.fail = tictactoe.fail.to_i + 1 if @host_won
    tictactoe.total = tictactoe.total.to_i + 1
    tictactoe.save
  end
#  
  def get_values(key)
    Rails.cache.read(key)
  end

  def update_user_values
    session[:user_values] = @user_picked_values
  end
  
  def update_host_values
    session[:host_values] = @host_picked_values
  end
  
  def update_valid_numbers
    session[:valid_numbers] = @valid_numbers
  end
  
  def initialize_value
    @choose_number = nil
    @host_won = false
    
    @game_id = session[:game_id] ||= 9
    @valid_numbers = session[:valid_numbers] ||= nil
    @user_picked_values = session[:user_values] ||= []
    @host_picked_values = session[:host_values] ||= []
    @possible_way_set ||= get_values("#{@game_id}X")
    @game_value ||= get_game_value(@game_id)
  end
  
  
  def set_default_values
    Rails.cache.write("9X", TicTacToeRule::POSSIBLE_3X3_SET)
    Rails.cache.write("16X", TicTacToeRule::POSSIBLE_4X4_SET)
    Rails.cache.write("25X", TicTacToeRule::POSSIBLE_5X5_SET)
    
    session[:valid_numbers] = session[:user_values] = session[:host_values] = nil
    @game_id = session[:game_id] ||= 9
    @possible_way_set = get_values("#{@game_id}X")
    @game_value = get_game_value(@game_id)
  end
  
  def get_game_value(id)
    case :id
    when "25"
      return 5
    when "16"
      return 4
    else
      return 3
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicTacToe</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="titactoe-header">
      <div class="container">
        <h2>Welcome to Tic Tac Toe Game</h2>
      </div>
      <div class="nav">
        <% unless current_user.nil? %>
          Welcome <%= current_user.email %> | <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
        <% end  %>
      </div>
    </div>

    <div class="container">
      <div class="row bdy">
        <%= yield %>
      </div>
    </div>

    <footer class="footer">
      <p>&copy; @ Rajesh Rajan</p>
    </footer>

  </body>
</html>

app/views/welcome/index.html.erb
<div class="game">
  <div class="game-size">Pick Game Plan: <%= link_to "3X3", game_change_path(:id => 9) %> | <%= link_to "4X4", game_change_path(:id => 16) %> | <%= link_to "5X5", game_change_path(:id => 25) %></div>
  <h5>Total Played: <%= current_user.tictactoe.total %>, Won: <%= current_user.tictactoe.pass %>, Lost: <%= current_user.tictactoe.fail %></h5>
  <div class="cell cell<%=@game_id%>">
  <% (1..@game_id.to_i).each do |i| %>
    <div id="cell_number_<%= i %>" val="<%= i %>"></div>
  <% end %>
  </div>
  <div class="clear"></div>
  <div class="button-link">
    <%= link_to "Reset", root_path, :class => 'btn btn-primary', :id => "reset" %>
  </div>
</div>  